import { app } from "/scripts/app.js";
const types=new Set(["YuE2AudioOutput","YuE2MidiOutput"]);
const fileUrl=(item,name)=>"/view?"+new URLSearchParams({filename:name,subfolder:item.subfolder,type:"output"});
function render(node,item){if(!node?._yue2Media||!item)return;const root=node._yue2Media;node.setSize([Math.max(500,node.size?.[0]||0),Math.max(item.kind==='midi'?510:450,node.size?.[1]||0)]);root.replaceChildren();const title=document.createElement('strong');title.textContent=item.title;root.append(title);const info=document.createElement('div');info.textContent=item.kind==='midi'?`MIDI簡易音源で試聴 / Synthetic audition · ${item.notes} notes`:`完成音声 / Generated audio · ${Number(item.seconds).toFixed(1)}秒`;root.append(info);const player=document.createElement('audio');player.controls=true;player.preload='metadata';player.src=fileUrl(item,item.play);Object.assign(player.style,{width:'100%',minHeight:'54px',flexShrink:'0'});root.append(player);
if(item.kind==='midi' && item.lyric_timeline?.length){
 const events=item.lyric_timeline;const karaoke=document.createElement('div');
 karaoke.setAttribute('aria-label','再生位置の歌詞 / Current lyrics');
 Object.assign(karaoke.style,{font:'bold 20px sans-serif',lineHeight:'1.8',minHeight:'72px',flexShrink:'0',padding:'8px',background:'#111827',borderRadius:'6px'});
 root.append(karaoke);let previous=-2;
 const update=()=>{let lo=0,hi=events.length;while(lo<hi){const mid=(lo+hi)>>1;if(events[mid].seconds<=player.currentTime)lo=mid+1;else hi=mid;}const current=lo-1;const resting=current>=0 && events[current].end_seconds!=null && player.currentTime>=events[current].end_seconds;const state=player.ended?'ended':resting?'rest'+current:current;if(state===previous)return;previous=state;karaoke.replaceChildren();
 if(player.ended){karaoke.textContent='✓ 再生完了 / Playback complete';return;}
 if(resting){karaoke.textContent='♪ 間奏・後奏 / Instrumental';return;}
 if(current<0){karaoke.textContent='♪ 前奏 / Intro';return;}
 const start=Math.max(0,current-8),end=Math.min(events.length,current+16);
 for(let i=start;i<end;i++){const span=document.createElement('span');span.textContent=events[i].text;span.style.color=i===current?'#111827':i<current?'#86efac':'#fff';if(i===current){span.style.background='#fde047';span.style.borderRadius='3px';}karaoke.append(span);}
 };
 for(const event of ['timeupdate','seeking','seeked','loadedmetadata','ended'])player.addEventListener(event,update);update();
}
const link=document.createElement('a');link.textContent=item.kind==='midi'?'⬇ MIDIをダウンロード / Download MIDI':'⬇ 音声FLACをダウンロード / Download audio';link.href=fileUrl(item,item.download);link.download=item.download;Object.assign(link.style,{display:'block',padding:'10px',background:'#166534',color:'#fff',fontWeight:'bold',borderRadius:'6px',textAlign:'center',textDecoration:'none'});root.append(link);const lyrics=document.createElement('pre');lyrics.textContent=item.lyrics||'';Object.assign(lyrics.style,{whiteSpace:'pre-wrap',overflowY:'auto',maxHeight:'180px',margin:'0',font:'14px sans-serif',lineHeight:'1.6'});root.append(lyrics);if(item.kind==='midi'){const note=document.createElement('small');note.textContent='歌詞入りMIDI（かな・仮割当）。歌詞と音符の対応は編集してください。試聴は簡易音源です。 / Lyrics MIDI with approximate kana alignment; edit note assignment. Synthetic audition.';root.append(note);}}
app.registerExtension({name:'yue2.mediaOutputs',onNodeOutputsUpdated(outputs){for(const [id,o] of Object.entries(outputs||{})){if(o?.yue2_media?.[0])render(app.graph?.getNodeById(id),o.yue2_media[0]);}},beforeRegisterNodeDef(Node,data){if(!types.has(data.name))return;const created=Node.prototype.onNodeCreated;Node.prototype.onNodeCreated=function(){const r=created?.apply(this,arguments);const root=document.createElement('div');Object.assign(root.style,{display:'flex',flexDirection:'column',gap:'8px',padding:'12px',background:'#202620',color:'#fff',boxSizing:'border-box',overflowY:'auto',font:'14px sans-serif'});root.textContent='実行後に再生とダウンロード / Run to play and download';this._yue2Media=root;this.addDOMWidget('media','yue2_media',root,{serialize:false,hideOnZoom:false,getValue:()=>'',setValue:()=>{}});this.setSize([500,data.name==='YuE2MidiOutput'?510:450]);return r;};const executed=Node.prototype.onExecuted;Node.prototype.onExecuted=function(o){const r=executed?.apply(this,arguments);render(this,o?.yue2_media?.[0]);return r;};}});